# This example uses yaml anchors which allows to name keys
# and re-use for multiple keys in a flexible way.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example
keys:
  - &admin 8BEE920B1C5FA4411EA8F59F1B8B7466F066A139
  - &prod_server b63e12c190329fb9c1a91c11a2bf18ad4d999283
  - &vm 27BAD88E87C18A972AC5D6DF54189C237851DE5D
creation_rules:
  - path_regex: secrets/vm.yaml
    key_groups:
    - pgp:
      - *vm
  - path_regex: secrets/prod.yaml
    key_groups:
    - pgp:
      - *admin
      - *prod_server
